version: "3.7"

services:
  mongo:
    image: mongo:5.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: $NB_MONGO__USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $NB_MONGO__PASSWORD
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data/db
#      - ./mongo/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro

volumes:
  mongo:
